env:
  matrix:
    - USE_OLDDECODER=false
    - USE_OLDDECODER=true
script:
  - mkdir -p m4
  - autoreconf --install
  - if [ "$USE_OLDDECODER" == "true" ]; then
      ./configure --enable-olddecoder;
    else
      ./configure;
    fi
  - make
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get update -qq;
        sudo apt-get install -y libdvbpsi-dev;
    else
        brew update;
        brew install libdvbpsi libhdhomerun;
    fi
language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
