#sudo: false
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - secure: "2TodR7XtmDQ3+HgX+wclWk4zU0nomFoNCuKWJ55oxBOiiVBBe6b+I2hLeEbFB8FO6S8tgUvr89dOWpTJAz8erRIaml4IVbNyDa+3kKnzbLkzbj1nWMIOvGWlFYeEjPPNMDp+cMVqg+MIS4rTHM/LhK/T9Bip5X+oaBDj9lcRU1b08Rit17ZNw8W8Gey3xOTCdV7ARl3nSOPALuhoW+GZaaPHB37Vblg9kIzeGrgDtwmR0P2gKxhNWh0Dr+sRRvQb4OYYGw6PGaVWpER28KB535vDSN0RzgvV/bR64isG+dPUmpf0+Q06KCOpvgud3mT4MIufOK0nFXISSSgzEyAKYJ1na1V0cKFG3D1FbkH6flIepI8L+gwFOnQwtS4Q7cOThdI2t8yWbScTQw02XAIOhaV6pBf5MfnxXNlhbpUDOVh1xZ1xDhcVIdLfE76ippTKhpymYXJAenE/drrRefC31SfKWVR2N2D3WqOA6TNyRocDoNVNQi7yCBx/tk6xChNvHVs0gK1MmSm0iomVLpZcqz+ReXQs/kCfv2bw/DnRJOd3NFFw8y9L8DKoThx1vRe5OX1zir+FnuPJFJRAw7FEIi2xh/iB5O38vlF4v0OZwjREo/zFsRdgD3zHYzXgp5821J7QDDI/rpFHCSLz+jxBVCxAL4cL8Y++dLfDUTHFBuQ="
      addons:
        apt:
          packages: ['libdvbpsi-dev','libhdhomerun-dev']
        coverity_scan:
          project:
            name: "mkrufky/libdvbtee"
            description: "Build submitted via Travis CI"
          notification_email: mkrufky@linuxtv.org
          build_command_prepend: "mkdir -p m4; autoreconf --install; ./configure; make clean"
          build_command:   "make -j"
          branch_pattern: coverity

## begin tests for DISABLE_HDHR with & without dependency

    - os: osx
      compiler: gcc
      env: DISABLE_HDHR=true

    - os: linux
      compiler: gcc
      env: BUILD_DVBPSI=true

    - os: linux
      compiler: gcc
      env: BUILD_DVBPSI=true USE_OLDDECODER=true

    - os: linux
      compiler: gcc
      env: DISABLE_HDHR=true
      addons:
        apt:
          packages: ['libdvbpsi-dev','libhdhomerun-dev']

    - os: linux
      compiler: gcc
      env: DISABLE_HDHR=true USE_OLDDECODER=true
      addons:
        apt:
          packages: ['libdvbpsi-dev','libhdhomerun-dev']

    - os: linux
      compiler: gcc
      env: DISABLE_HDHR=true
      addons:
        apt:
          packages: ['libdvbpsi-dev']

    - os: linux
      compiler: gcc
      env: DISABLE_HDHR=true USE_OLDDECODER=true
      addons:
        apt:
          packages: ['libdvbpsi-dev']

##   end tests for DISABLE_HDHR with & without dependency

    - os: osx
      compiler: gcc

    - os: osx
      compiler: gcc
      env: USE_OLDDECODER=true

    - os: osx
      compiler: gcc
      env: BUILD_DVBPSI=true

    - os: osx
      compiler: gcc
      env: BUILD_DVBPSI=true USE_OLDDECODER=true

    - os: osx
      compiler: clang

    - os: osx
      compiler: clang
      env: USE_OLDDECODER=true

    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['libdvbpsi-dev']

    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['libdvbpsi-dev']
      env: USE_OLDDECODER=true

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libdvbpsi-dev', 'g++-4.8']
      env: COMPILER=g++-4.8 GCOV=gcov-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libdvbpsi-dev', 'g++-4.8']
      env: COMPILER=g++-4.8 GCOV=gcov-4.8 USE_OLDDECODER=true

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libdvbpsi-dev', 'g++-4.9']
      env: COMPILER=g++-4.9 GCOV=gcov-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libdvbpsi-dev', 'g++-4.9']
      env: COMPILER=g++-4.9 GCOV=gcov-4.9 USE_OLDDECODER=true

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libdvbpsi-dev', 'g++-5']
      env: COMPILER=g++-5 GCOV=gcov-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libdvbpsi-dev', 'g++-5']
      env: COMPILER=g++-5 GCOV=gcov-5 USE_OLDDECODER=true

    - os: linux
      compiler: clang
      addons:
        apt:
          packages: ['libdvbpsi-dev']

    - os: linux
      compiler: clang
      addons:
        apt:
          packages: ['libdvbpsi-dev']
      env: USE_OLDDECODER=true

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['libdvbpsi-dev', 'clang-3.5']
      env: COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['libdvbpsi-dev', 'clang-3.5']
      env: COMPILER=clang++-3.5 USE_OLDDECODER=true

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['libdvbpsi-dev', 'clang-3.6']
      env: COMPILER=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['libdvbpsi-dev', 'clang-3.6']
      env: COMPILER=clang++-3.6 USE_OLDDECODER=true

# Activate when 3.7 is released and the repository is available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
#          packages: ['libdvbpsi-dev', 'clang-3.7']
#      env: COMPILER=clang++-3.7

# Activate when 3.7 is released and the repository is available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
#          packages: ['libdvbpsi-dev', 'clang-3.7']
#      env: COMPILER=clang++-3.7 USE_OLDDECODER=true

install:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - if [ x"$GCOV" != "x" ]; then
      sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/$GCOV 90;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz;
      tar xf lcov_1.11.orig.tar.gz;
      sudo make -C lcov-1.11/ install;
      gem install coveralls-lcov;
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      lcov --directory . --zerocounters;
    fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      lcov --directory . --capture --output-file coverage.info;
      lcov --remove coverage.info 'examples/*' '/usr/*' '/dvbtee/*' 'libdvbtee_server/*' --output-file coverage.info;
      lcov --list coverage.info;
      coveralls-lcov --repo-token ZmCWNStr6D9Dga7i8raNa1Jyhf7slUykK coverage.info;
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - mkdir -p m4
  - autoreconf --install
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then
      if [ "$BUILD_DVBPSI" == "true" ]; then
        if [ "$USE_OLDDECODER" == "true" ]; then
          ./build-auto.sh --enable-olddecoder;
        else
          ./build-auto.sh;
        fi;
      else if [ "$DISABLE_HDHR" == "true" ]; then
        if [ "$USE_OLDDECODER" == "true" ]; then
          ./configure --disable-hdhr --enable-olddecoder;
        else
          ./configure --disable-hdhr;
        fi;
      else
        if [ "$USE_OLDDECODER" == "true" ]; then
          ./configure --enable-olddecoder;
        else
          ./configure;
        fi;
      fi; fi;
    else
      if [ "$BUILD_DVBPSI" == "true" ]; then
        if [ "$USE_OLDDECODER" == "true" ]; then
          ./build-auto.sh --enable-olddecoder CXXFLAGS="--coverage" --enable-coveralls;
        else
          ./build-auto.sh CXXFLAGS="--coverage" --enable-coveralls;
        fi;
      else if [ "$DISABLE_HDHR" == "true" ]; then
        if [ "$USE_OLDDECODER" == "true" ]; then
          ./configure --disable-hdhr --enable-olddecoder CXXFLAGS="--coverage" --enable-coveralls;
        else
          ./configure --disable-hdhr CXXFLAGS="--coverage" --enable-coveralls;
        fi;
      else
        if [ "$USE_OLDDECODER" == "true" ]; then
          ./configure --enable-olddecoder CXXFLAGS="--coverage" --enable-coveralls;
        else
          ./configure CXXFLAGS="--coverage" --enable-coveralls;
        fi;
      fi; fi;
    fi
  - if [ x"$COMPILER" == "x" ]; then
      make -j;
    else
      make CXX=$COMPILER -j;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://trac.ffmpeg.org/raw-attachment/ticket/3025/sbs.2.5M.ts;
      wget http://www.dododge.net/roku/hd-test-streams/football.ts;
      make check;
    fi

before_install:
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then
        brew update;
        brew install libdvbpsi libhdhomerun;
    fi
