os: Visual Studio 2015
build_script:
  - set QTDIR=C:\Qt\5.4\mingw491_32
  - set MINGWDIR=C:\MinGW
  - set PATH=%QTDIR%\bin;%PATH%
  - set PATH=%MINGWDIR%\bin;%PATH%
  - set PATH=C:\msys64\usr\bin;%PATH%
  - cd C:\projects\libdvbtee\
  - mingw-get install mingw32-pthreads-w32
  - ps: C:\msys64\usr\bin\sh.exe --login /c/projects/libdvbtee/build-auto.sh
